"""Recording measured values against the §18 replication targets.

Every replication test calls `record_result` with what it measured; the log
itself is a materialized view of `artifacts/replication_results.jsonl`,
regenerated by `scripts/generate_replication_log.py` (brief §18: "Each test
writes its measured value and target to docs/REPLICATION_LOG.md ...
regenerated on every run").
"""

from __future__ import annotations

import json
from pathlib import Path

RESULTS_PATH = Path("artifacts/replication_results.jsonl")


def record_result(
    name: str,
    value: float,
    target: str,
    tolerance: str,
    passed: bool,
    units: str = "",
) -> None:
    RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "name": name,
        "value": value,
        "target": target,
        "tolerance": tolerance,
        "passed": bool(passed),
        "units": units,
    }
    with RESULTS_PATH.open("a") as f:
        f.write(json.dumps(entry) + "\n")
