#!/usr/bin/env python
"""Regenerate docs/REPLICATION_LOG.md from artifacts/replication_results.jsonl.

Run after any replication-tier test run: `make replicate` does this
automatically. Keeps only the most recent entry per test name.
"""

from __future__ import annotations

import json
from pathlib import Path

RESULTS_PATH = Path("artifacts/replication_results.jsonl")
LOG_PATH = Path("docs/REPLICATION_LOG.md")


def main() -> None:
    entries: dict[str, dict] = {}
    if RESULTS_PATH.exists():
        for line in RESULTS_PATH.read_text().splitlines():
            if not line.strip():
                continue
            e = json.loads(line)
            entries[e["name"]] = e  # last write wins

    lines = [
        "# Replication Log",
        "",
        "Auto-generated by `scripts/generate_replication_log.py` from "
        "`artifacts/replication_results.jsonl`. Do not edit by hand.",
        "",
        "| test | measured | target | tolerance | status |",
        "|---|---|---|---|---|",
    ]
    for name in sorted(entries):
        e = entries[name]
        status = "PASS" if e["passed"] else "**FAIL**"
        value = e["value"]
        value_str = f"{value:.4g}" if isinstance(value, (int, float)) else str(value)
        units = f" {e['units']}" if e.get("units") else ""
        lines.append(
            f"| `{name}` | {value_str}{units} | {e['target']} | {e['tolerance']} | {status} |"
        )
    LOG_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {LOG_PATH} ({len(entries)} entries).")


if __name__ == "__main__":
    main()
